services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: TELEGRAM_TOKEN
        sync: false
      - key: CHANNEL_USERNAME
        sync: false
      - key: UNSPLASH_ACCESS_KEY
        sync: false
      - key: DEFAULT_TOPIC
        sync: false
      - key: POST_TIMES
        sync: false
